'use client'

import { useState } from 'react'
import {
  ArrowLeftRight, BookOpen, Check, ChevronRight, CircleHelp, CloudOff, Download, FileText,
  FolderOpen, Headphones, Home, LockKeyhole, Menu, Mic, MoreHorizontal, Play, RotateCcw,
  Settings, ShieldCheck, SlidersHorizontal, Sparkles, Volume2, Waves, WifiOff, X
} from 'lucide-react'

const maroon = '#7a3226'
const tabs = [
  { id: 'home', label: 'होम', icon: Home }, { id: 'translator', label: 'अनुवादक', icon: Waves },
  { id: 'curriculum', label: 'पाठ्यक्रम', icon: BookOpen }, { id: 'worksheets', label: 'कार्यपत्रक', icon: FileText },
  { id: 'storage', label: 'संग्रह', icon: FolderOpen },
]

function StatusStrip() { return <div className="status-strip"><span className="status-dot" /> क्लाउड अनुवाद सक्रिय <span className="status-note">(डेमो चरण)</span><span className="status-right">◷ 09:42</span></div> }
function Header({ title, onSettings }: { title: string, onSettings: () => void }) { return <header className="app-header"><div className="brand-mark">से</div><div className="brand-copy"><strong>SETU <span>सेतु</span></strong><small>{title}</small></div><div className="pair-chip">हिन्दी <ArrowLeftRight size={13} /> संथाली</div><button className="avatar" onClick={onSettings} aria-label="सेटिंग्स खोलें">अशि</button></header> }
function SectionTitle({ children, action }: { children: React.ReactNode, action?: string }) { return <div className="section-title"><h2>{children}</h2>{action && <button className="text-action">{action} <ChevronRight size={15} /></button>}</div> }
function MicButton({ small = false }: { small?: boolean }) { return <button className={`mic-button ${small ? 'small' : ''}`} aria-label="माइक दबाकर बोलें"><Mic size={small ? 22 : 30} /></button> }

function HomeScreen({ go }: { go: (s: string) => void }) {
  return <><div className="language-switch"><button className="active">संथाली</button><button>हिन्दी</button><ArrowLeftRight size={22} /></div>
    <section className="hero-card"><div><span className="eyebrow">कक्षा में तुरंत सहायता</span><h1>कक्षा अनुवाद</h1><p>सीधा बोलकर अनुवाद करें</p><button className="hero-cta" onClick={() => go('translator')}><Mic size={19} /> बोलना शुरू करें</button><small>माइक दबाकर बोलें</small></div><div className="hero-orb"><Mic size={48} /></div></section>
    <SectionTitle action="सभी पाठ">आज का पाठ</SectionTitle><section className="lesson-card"><div className="lesson-image"><div className="sun" /><div className="hut" /><div className="tree" /></div><div className="lesson-content"><span className="tag">भाषा • कक्षा ३</span><h3>हमारा सुंदर गाँव</h3><p>अपने गाँव और आसपास की चीज़ों के बारे में सीखें।</p><div className="lesson-actions"><button className="primary-btn" onClick={() => go('curriculum')}>पाठ शुरू करें</button><button className="secondary-btn"><BookOpen size={16} /> शब्दावली</button></div></div></section>
    <SectionTitle action="और देखें">त्वरित भाषा सामग्री</SectionTitle><div className="media-row"><MediaCard kind="बालगीत" title="चलो गाएँ" icon="♫" /><MediaCard kind="कहानी" title="चतुर चिड़िया" icon="◉" /></div>
    <div className="success-banner"><Check size={20} /><div><strong>संथाली भाषा पैक तैयार</strong><span>आप बिना इंटरनेट भी पाठ चला सकते हैं</span></div></div><div className="footer-cards"><div><Sparkles size={18} /><strong>भाषा सेतु पैक</strong><small>१२४ वाक्य उपलब्ध</small></div><div><Headphones size={18} /><strong>दैनिक बालगीत</strong><small>आज का गीत सुनें</small></div></div></>
}
function MediaCard({ kind, title, icon }: { kind: string, title: string, icon: string }) { return <div className="media-card"><div className="media-thumb">{icon}</div><div><span>{kind}</span><strong>{title}</strong></div><button aria-label="चलाएं"><Play size={16} fill="currentColor" /></button></div> }
function TranslatorScreen() { return <><div className="mode-toggle"><button className="active">दबाकर बोलें</button><button>लगातार सुनें</button></div><div className="context-label">कक्षा ३ <span>•</span> FLN वाचन <span className="live-pill">Bhashini demo</span></div><div className="speech-card"><span className="bubble-label">आपने कहा • हिन्दी</span><p>“बच्चों, किताब खोलो और पहला पन्ना पढ़ो।”</p><button><Volume2 size={17} /></button></div><div className="translation-card"><div className="translation-head"><span className="bubble-label">संथाली अनुवाद</span><span className="verified"><ShieldCheck size={14} /> सत्यापित</span></div><p className="olchiki">ᱵᱟᱹᱲᱤ ᱠᱚ, ᱯᱟᱹᱛᱤ ᱠᱷᱚᱞ ᱢᱮ</p><div className="word-chips"><span>ᱵᱟᱹᱲᱤ <small>children</small> <Volume2 size={12} /></span><span>ᱯᱟᱹᱛᱤ <small>book</small> <Volume2 size={12} /></span><span>ᱠᱷᱚᱞ <small>open</small> <Volume2 size={12} /></span></div></div><div className="listen-area"><MicButton /><strong>माइक दबाकर बोलें</strong><span>बोलते ही संथाली में अनुवाद सुनाया जाएगा</span></div><div className="replay-bar"><RotateCcw size={17} /> पिछला वाक्य दोहराएं <Volume2 size={17} /></div><div className="quick-actions"><button><Volume2 size={18} /> शांत रहें</button><button><Sparkles size={18} /> शाबाश!</button></div><div className="inline-warning"><WifiOff size={16} /> इंटरनेट उपलब्ध नहीं — बाद में पुनः प्रयास करें</div></> }
function CurriculumScreen({ go }: { go: (s: string) => void }) { const rows = [['१','बच्चों, किताब खोलो।','ᱵᱟᱹᱲᱤ ᱠᱚ, ᱯᱟᱹᱛᱤ ᱠᱷᱚᱞ ᱢᱮ','किताब'],['२','पहला पन्ना पढ़ो।','ᱯᱟᱹᱛᱤ ᱨᱮᱭᱟᱜ ᱢᱤᱫ ᱯᱟᱱᱟ ᱯᱟᱲᱦᱟᱣ ᱢᱮ','पन्ना'],['३','चित्र को ध्यान से देखो।','ᱪᱤᱛᱟᱹᱨ ᱠᱚ ᱧᱮᱞ ᱢᱮ','चित्र']]; return <><div className="lesson-heading"><span className="tag">भाषा • कक्षा ३</span><button><ArrowLeftRight size={18} /></button><h1>हमारा सुंदर गाँव</h1><p>गाँव की चीज़ों को पहचानना और उनके नाम सीखना।</p></div><div className="sentence-list">{rows.map(r => <div className="sentence-card" key={r[0]}><b>{r[0]}</b><div><strong>{r[1]}</strong><p className="olchiki">{r[2]}</p><span className="key-chip">मुख्य शब्द: {r[3]}</span></div><button className="play-btn"><Volume2 size={18} /> सुनें</button></div>)}</div><div className="activity-card"><div className="folk-art"><span>◒</span><span>⌁</span><span>◓</span></div><div><span className="eyebrow">कक्षा गतिविधि</span><p>बच्चों से अपने गाँव का चित्र बनवाएँ।</p></div></div><div className="sticky-controls"><button className="primary-btn"><Play size={16} fill="currentColor" /> पूरा पाठ सुनाएं</button><button className="secondary-btn" onClick={() => go('worksheets')}>कार्यपत्रक देखें</button></div></> }
function StorageScreen() { return <><div className="cloud-banner"><CloudOff size={23} /><div><strong>बिना इंटरनेट के पूरा उपयोग</strong><span>डाउनलोड किए पाठ आपके टैबलेट में सुरक्षित हैं</span></div></div><div className="device-card"><div><span className="eyebrow">टैबलेट स्थिति</span><h3>सब कुछ ठीक है</h3></div><span className="ready-pill"><Check size={14} /> तैयार</span></div><SectionTitle>ऑफ़लाइन पाठ सामग्री</SectionTitle><div className="download-list">{[['संथाली भाषा पैक','१२४ वाक्य और शब्दावली','तैयार (सक्रिय)'],['कक्षा ३ • भाषा','८ पाठ और गतिविधियाँ','तैयार'],['दैनिक बालगीत','२८ ऑडियो गीत','तैयार']].map((x,i) => <div className="download-row" key={x[0]}><div className="list-icon">{i===0?<Waves size={18}/>:i===1?<BookOpen size={18}/>:<Headphones size={18}/>}</div><div><strong>{x[0]}</strong><small>{x[1]}</small></div><span className="ready-pill">{x[2]}</span></div>)}</div><div className="sync-card"><span className="eyebrow">नया पाठ अपडेट करें</span><p>पिछला सिंक: आज, 08:15 बजे</p><button className="primary-btn"><Download size={17} /> पाठ व भाषा सामग्री सिंक करें</button><small>स्कूल में इंटरनेट मिलने पर दबाएं</small></div><div className="footer-links"><button>मेमोरी खाली करें</button><button>उन्नत सेटिंग्स</button></div></> }
function WorksheetsScreen() { return <><div className="selector-row"><div><span>कक्षा और इकाई</span><strong>कक्षा ३ • इकाई १</strong></div><button>बदलें <ChevronRight size={15} /></button></div><div className="work-tabs"><button className="active">सचित्र फ़्लैशकार्ड</button><button>प्रिंट कार्यपत्रक</button></div><div className="flashcard"><div className="flash-art"><div className="art-sun" /><div className="art-hill" /><div className="art-house">⌂</div><span className="card-count">कार्ड ०३ / १२</span><span className="level-tag">कक्षा ३</span></div><div className="flash-content"><span className="eyebrow">हिन्दी शब्द</span><h1>गाँव</h1><div className="olive-chip">ᱦᱟᱛᱩ <Volume2 size={17} /></div><p>“मेरा गाँव बहुत सुंदर है।”</p><p className="olchiki">“ᱤᱧᱟᱹᱜ ᱦᱟᱛᱩ ᱵᱟᱹᱲᱤ ᱥᱩᱱᱫᱟᱹᱨ ᱜᱮᱭᱟ।”</p></div></div><button className="next-card">अगला कार्ड <ChevronRight size={18} /></button></> }
function SettingsScreen() { return <><div className="profile-card"><div className="profile-avatar">अशि</div><div><h2>आशा मुर्मू</h2><p>सहायक शिक्षक • प्राथमिक विद्यालय</p><small>सत्र २०२५–२६</small></div><span className="verified"><ShieldCheck size={14} /> सत्यापित संकुल</span></div><SectionTitle>भाषा विस्तार रोडमैप</SectionTitle><div className="roadmap">{[['संथाली','तैयार और सक्रिय','green'],['हो','प्रशिक्षण जारी','amber'],['मुंडारी','डेटा संग्रह जारी','gray']].map(x => <div><span className={`road-dot ${x[2]}`} /><strong>{x[0]}</strong><small>{x[1]}</small><ChevronRight size={16} /></div>)}</div><section className="contribution-card"><span className="eyebrow">शिक्षक सहभागिता</span><h2>अपनी बोली से सेतु बनाएँ</h2><p>मॉडल को बेहतर बनाने के लिए ५ छोटे वाक्य रिकॉर्ड करें।</p><div className="sample-line">“बच्चों, आज हम पेड़ के बारे में सीखेंगे।”</div><button className="record-btn"><Mic size={18} /> अपनी आवाज़ जोड़ें</button></section><SectionTitle>पठन व ध्वनि प्राथमिकताएं</SectionTitle><div className="preference-row"><span><SlidersHorizontal size={18} /> अक्षर का आकार</span><b>सामान्य　/　बड़ा आकार</b></div><div className="preference-row"><span><Mic size={18} /> माइक शोर निवारक</span><div className="switch on"><i /></div></div><div className="help-row"><CircleHelp size={20} /><div><strong>सहायता एवं संकुल संपर्क</strong><small>समन्वयक: रमेश हेम्ब्रम • ☎ 1800-123-SETU</small></div><ChevronRight size={17} /></div><footer>SETU सेतु • संस्करण 1.0.0 (डेमो)</footer></> }

export default function Page() { const [screen, setScreen] = useState('home'); const [settings, setSettings] = useState(false); const titles: Record<string,string> = { home:'आपका आज का शिक्षण साथी', translator:'बोलें और सीखें', curriculum:'पाठ और वाक्य अभ्यास', worksheets:'देखें, बोलें, सीखें', storage:'आपकी सामग्री', settings:'सेटिंग्स' }; const active = settings ? 'settings' : screen; return <div className="tablet-shell"><StatusStrip /><Header title={titles[active]} onSettings={() => setSettings(true)} /><main className="screen-content">{active==='home'&&<HomeScreen go={s=>{setScreen(s);setSettings(false)}} />}{active==='translator'&&<TranslatorScreen />}{active==='curriculum'&&<CurriculumScreen go={s=>setScreen(s)} />}{active==='worksheets'&&<WorksheetsScreen />}{active==='storage'&&<StorageScreen />}{active==='settings'&&<SettingsScreen />}</main><nav className="bottom-nav">{tabs.map(t => { const Icon=t.icon; return <button className={active===t.id?'active':''} onClick={()=>{setScreen(t.id);setSettings(false)}} key={t.id}><Icon size={21}/><span>{t.label}</span></button>})}</nav></div> }

function _unused() { return <><Menu/><LockKeyhole/><MoreHorizontal/><X/></> }

const styles = ''
export { maroon }
